runtime: python37

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 4
  max_instances: 100
  min_pending_latency: 30ms 
  max_pending_latency: automatic
  max_concurrent_requests: 50